main:
  dataset: competition_and_livecell
  task: instance_segmentation

model_parameters:
  model_name: competition_and_livecell_mask_rcnn
  model_path: ../models/livecell/instance_segmentation
  model_class: MaskRCNNModel
  model_checkpoint_path: null
  model_class_parameters:
    num_classes: 10
    fpn: maskrcnn_resnet50_fpn
    pretrained: True
    pretrained_backbone: True
    trainable_backbone_layers: null
    mask_predictor_hidden_dim: 256
    min_size: 800
    max_size: 1333
    image_mean:
      - 0.5020363330161387
      - 0.5020363330161387
      - 0.5020363330161387
    image_std:
      - 0.043813150267825875
      - 0.043813150267825875
      - 0.043813150267825875
    box_detections_per_img: 550

training_parameters:
  training_set:
    - livecell_train
    - livecell_val
    - livecell_test
    - competition_non_noisy_split
  optimizer: SGD
  optimizer_parameters:
    lr: 0.001
    momentum: 0.9
    weight_decay: 0
  lr_scheduler: CosineAnnealingLR
  lr_scheduler_parameters:
    T_max: 250
    eta_min: 0.0001
    last_epoch: -1
    verbose: False
  data_loader:
    training_batch_size: 4
    test_batch_size: 16
    num_workers: 4
  epochs: 120
  early_stopping_patience: 15
  deterministic_cudnn: False
  device: cuda
  random_state: 42

transform_parameters:
  horizontal_flip_probability: 0.5
  vertical_flip_probability: 0.5
  random_rotate_90_probability: 0.25
  shift_limit: 0.0125
  scale_limit: 0.05
  rotate_limit: 0
  shift_scale_rotate_probability: 0.25
  brightness_limit: 0.25
  contrast_limit: 0.25
  brightness_contrast_probability: 0.25

