DATASET:
  training_set_name: train_clean_polygon_stratified_fold1
  test_set_name: val_clean_polygon_stratified_fold1
  image_root: ../data

MODEL:
  model_zoo_path: ../venv/lib/python3.8/site-packages/centermask2/configs/centermask/centermask_V_99_eSE_dcn_FPN_ms_3x.yaml
  pretrained_model_path: ../venv/lib/python3.8/site-packages/centermask2/configs/centermask/centermask_V_99_eSE_dcn_FPN_ms_3x.yaml
  eval_model_path: null