DATASET:
  training_set_name: train_stratified_fold1
  test_set_name: val_stratified_fold1
  image_root: ../data

MODEL:
  path: COCO-InstanceSegmentation/mask_rcnn_R_101_FPN_3x.yaml

AUGMENTATIONS:
  HorizontalFlip:
    p: 0.5
  VerticalFlip:
    p: 0.5
  RandomRotate90:
    p: 0.25
  ShiftScaleRotate:
    shift_limit: 0.0125
    scale_limit: 0.05
    rotate_limit: 0
    p: 0.25
  RandomBrightnessContrast:
    brightness_limit: 0.25
    contrast_limit: 0.25
    p: 0.25
